name: drugs_ng
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  # blur: ^3.1.0
  dio: ^5.2.1+1
  dotted_border: ^2.1.0
  dropdown_button2: ^2.3.9
  either_dart: ^1.0.0
  encrypt: ^5.0.3
  equatable: ^2.0.5
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_carousel_widget: ^2.2.0
  flutter_countdown_timer: ^4.1.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.6
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  location: null
  page_transition: ^2.1.0
  persistent_bottom_nav_bar_v2: ^5.2.3
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/test_image/
    - assets/svg/
    - assets/fonts/
    - assets/json/

  fonts:
    - family: Sf-Pro-Display
      fonts:
        - asset: assets/fonts/Sf-Pro-Display-Thin.otf
          weight: 100
        - asset: assets/fonts/Sf-Pro-Display-Ultralight.otf
          weight: 200
        - asset: assets/fonts/Sf-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/Sf-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/Sf-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/Sf-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/Sf-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/Sf-Pro-Display-Black.otf
          weight: 800
        - asset: assets/fonts/Sf-Pro-Display-Heavy.otf
          weight: 900
